# Site wide configuration

title:            Betan
locale:           en_US
url:              http://www.betan.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner: 
  name: Elísabet Ólafsdóttir
  avatar: biopic.png
  bio: "Húsfrú úr Háaleitinu. Þjáist af alvarlegri geðlægð, kvíða og loddaraheilkenni e. impostor syndrome. Blogga til að batna í samvinnu við Virk endurhæfingu."
  email: elisabet.olafsdottir@gmail.com
  disqus-shortname: 
  twitter: betan
  facebook: betan
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: betan
  instagram: beddarinn
  lastfm: #username
  tumblr: #username
  pinterest: beddarinn
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: beddarinn
  soundcloud: betan-1
  weibo: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
